#!/bin/bash

# Install git
sudo apt-get install git-core

localdir="$HOME/cayuga"

if [ -d "$localdir" ]; then
    rm -rf "$localdir"
fi

# Clone a read-only copy of the management scripts repository
cd $HOME
git clone git://github.com/kixxauth/cayuga.git

# Update Ubuntu and install dependencies
sudo "$localdir/bin/bootstrap_ubuntu"

PATH="$localdir/bin:$PATH"

echo "OK - toehold is done"
